import type { Meta, StoryObj } from "@storybook/react-vite";

import { CodeBlock, CodeBlockCode, CodeBlockGroup } from "@/atoms/code-block";
import { CopyButton } from "@/atoms/copy-button";

// ============================================
// Mock Data
// ============================================

const CAMPAIGN_CONFIG_JSON = `{
  "campaignName": "SP - Wireless Headphones - Exact",
  "marketplace": "amazon.com",
  "dailyBudget": 150.0,
  "targetAcos": 0.22,
  "keywords": [
    { "text": "wireless headphones", "matchType": "exact", "bid": 1.35 },
    { "text": "noise cancelling headphones", "matchType": "phrase", "bid": 1.1 }
  ]
}`;

const PRICING_RULE_TS = `export const buyBoxDefenseRule: PricingRule = {
  asin: "B08XYZ1234",
  trigger: "buy_box_lost",
  action: {
    type: "adjust_price",
    strategy: "match_competitor_minus",
    offsetCents: -20,
    minMarginPct: 0.28,
  },
};`;

const BASH_SNIPPET = String.raw`curl -X POST https://api.commerceiq.ai/v1/pricing-rules \
  -H "Authorization: Bearer <token>" \
  -d '{"asin":"B08XYZ1234","action":"apply"}'`;

// ============================================
// Story Configuration
// ============================================

const meta: Meta<typeof CodeBlock> = {
  title: "Atoms/CodeBlock",
  component: CodeBlock,
  parameters: {
    layout: "padded",
    docs: {
      description: {
        component: `
A syntax-highlighted code block (via Shiki), used in Sales Agent and
Content Agent transcripts to show generated config, API payloads, or
pricing rule snippets. Compose it from \`CodeBlock\` (frame),
\`CodeBlockGroup\` (header row, e.g. for a language label + copy button),
and \`CodeBlockCode\` (the highlighted code itself). Highlighting happens
asynchronously on mount.
        `,
      },
    },
  },
  tags: ["autodocs"],
  argTypes: {
    children: {
      control: false, // composed from CodeBlockGroup/CodeBlockCode, see render functions
      description: "Code block content, typically a CodeBlockGroup header and a CodeBlockCode.",
    },
    className: {
      control: false, // styling escape hatch, not meaningful via controls
      description: "Additional class names for the outer frame.",
    },
  },
};

export default meta;
type Story = StoryObj<typeof CodeBlock>;

// ============================================
// Stories
// ============================================

/** JSON campaign config, as generated by a Retail Media Management agent action. */
export const Default: Story = {
  render: (args) => (
    <CodeBlock {...args} className="w-[520px]">
      <CodeBlockCode code={CAMPAIGN_CONFIG_JSON} language="json" />
    </CodeBlock>
  ),
};

/** With a header row showing the language and a copy-to-clipboard action. */
export const WithHeaderAndCopyButton: Story = {
  render: (args) => (
    <CodeBlock {...args} className="w-[520px]">
      <CodeBlockGroup className="border-b px-4 py-2 text-xs text-muted-foreground">
        pricing-rule.ts
        <CopyButton value={PRICING_RULE_TS} />
      </CodeBlockGroup>
      <CodeBlockCode code={PRICING_RULE_TS} language="ts" />
    </CodeBlock>
  ),
};

/** Shell/bash snippet, e.g. an example API call shown in developer docs. */
export const BashSnippet: Story = {
  render: (args) => (
    <CodeBlock {...args} className="w-[520px]">
      <CodeBlockGroup className="border-b px-4 py-2 text-xs text-muted-foreground">
        Terminal
        <CopyButton value={BASH_SNIPPET} />
      </CodeBlockGroup>
      <CodeBlockCode code={BASH_SNIPPET} language="bash" />
    </CodeBlock>
  ),
};

/** Unrecognized/unsupported language falls back to plaintext highlighting. */
export const UnknownLanguageFallback: Story = {
  render: (args) => (
    <CodeBlock {...args} className="w-[520px]">
      <CodeBlockCode code={CAMPAIGN_CONFIG_JSON} language="graphql" />
    </CodeBlock>
  ),
};
