// Schema types (including re-exports from data.ts and widget.ts)
export type {
  ActionConfig,
  APIComparePeriodPayload,
  APIFilterAllClause,
  APIFilterAnyClause,
  APIFilterCondition,
  APIFilterNot,
  APIFilterOperator,
  APIFilterPayload,
  APIFilterWhereClause,
  APIPaginationPayload,
  APIRequestPayload,
  APIResponsePayload,
  APISelectPayload,
  APISortItem,
  APISortPayload,
  BaseDataTableContent,
  BreakdownDimension,
  Cadence,
  ColumnRole,
  ColumnSchema,
  ColumnWithKey,
  CompareCadence,
  DataSource,
  DateRangeMetadata,
  ExtendedPageInfo,
  FilterCombinationOperator,
  FilterMetadata,
  FilterOperator,
  FlatResponse,
  GranularityActionConfig,
  HeaderMenuConfig,
  PaginationMetadata,
  ResponseMetadata,
  SKUMetadata,
  SortConfig,
  SortConfigItem,
  TableOptions,
  TableSchema,
  TimeGranularity,
  Visibility,
  WidgetActions,
  WidgetBehavior,
  WidgetBody,
  WidgetInsights,
  WidgetLayout,
  WidgetMetadata,
  WidgetTop,
  WidgetTopV2,
  WidgetV2Schema,
} from "./schema";
export { CADENCE, COLUMN_ROLE, COMPARE_CADENCE } from "./schema";

// Table component types
export type {
  AugmentedRow,
  AugmentedRowFields,
  BaseDataTableColumnDef,
  BaseDataTableColumnMeta,
  BaseDataTableContextValue,
  BaseDataTableFeatures,
  BaseDataTableProps,
  BaseDataTableState,
  BaseDataTableStateHandlers,
  BreakdownConfigError,
  BreakdownConfigFromSchema,
  CellRegistryType,
  CellRenderer,
  CellRendererProps,
  ColumnPinningState,
  ExpandConfig,
  HeaderRenderer,
  HeaderRendererProps,
  RegisteredCellRenderer,
  RegisteredCellRendererProps,
  RenderEmptyStateProps,
  RenderErrorStateProps,
  RenderFiltersProps,
  RenderPaginationProps,
  RowBreakdownConfig,
  SpecialRowRenderer,
  SpecialRowRendererProps,
  SubRowCacheEntry,
  VirtualizationOptions,
} from "./table";

// Action types
export type { HeaderAction, HideAction, PinAction, SortAction } from "./actions";

// Hook types (from table.ts)
export type {
  FetchDataCallback,
  UseBaseDataTableDataOptions,
  UseBaseDataTableDataReturn,
} from "./table";

// State helpers used by hooks / hosts
export type { PartialStateUpdater } from "../utils/state-utils";
